/**
 * EUI Icon Cache - COMPLETE EDITION
 * 
 * AUTO-GENERATED by scripts/generate-all-icons.cjs
 * DO NOT EDIT MANUALLY
 * 
 * This file imports ALL 520 EUI icons to ensure no icon is ever missing.
 * Bundle size impact: ~200-300KB (acceptable for demos)
 * 
 * Regenerate with: node scripts/generate-all-icons.cjs
 */
import { appendIconComponentCache } from '@elastic/eui/es/components/icon/icon'

import { icon as accessibility } from '@elastic/eui/es/components/icon/assets/accessibility'
import { icon as aggregate } from '@elastic/eui/es/components/icon/assets/aggregate'
import { icon as alert } from '@elastic/eui/es/components/icon/assets/alert'
import { icon as analyzeEvent } from '@elastic/eui/es/components/icon/assets/analyzeEvent'
import { icon as analyzeEvent1 } from '@elastic/eui/es/components/icon/assets/analyze_event'
import { icon as annotation } from '@elastic/eui/es/components/icon/assets/annotation'
import { icon as anomalyChart } from '@elastic/eui/es/components/icon/assets/anomaly_chart'
import { icon as anomalySwimLane } from '@elastic/eui/es/components/icon/assets/anomaly_swim_lane'
import { icon as apmTrace } from '@elastic/eui/es/components/icon/assets/apm_trace'
import { icon as appAddData } from '@elastic/eui/es/components/icon/assets/app_add_data'
import { icon as appAdvancedSettings } from '@elastic/eui/es/components/icon/assets/app_advanced_settings'
import { icon as appAgent } from '@elastic/eui/es/components/icon/assets/app_agent'
import { icon as appApm } from '@elastic/eui/es/components/icon/assets/app_apm'
import { icon as appAppSearch } from '@elastic/eui/es/components/icon/assets/app_app_search'
import { icon as appAuditbeat } from '@elastic/eui/es/components/icon/assets/app_auditbeat'
import { icon as appCanvas } from '@elastic/eui/es/components/icon/assets/app_canvas'
import { icon as appCases } from '@elastic/eui/es/components/icon/assets/app_cases'
import { icon as appCode } from '@elastic/eui/es/components/icon/assets/app_code'
import { icon as appConsole } from '@elastic/eui/es/components/icon/assets/app_console'
import { icon as appCrossClusterReplication } from '@elastic/eui/es/components/icon/assets/app_cross_cluster_replication'
import { icon as appDashboard } from '@elastic/eui/es/components/icon/assets/app_dashboard'
import { icon as appDevtools } from '@elastic/eui/es/components/icon/assets/app_devtools'
import { icon as appDiscover } from '@elastic/eui/es/components/icon/assets/app_discover'
import { icon as appEms } from '@elastic/eui/es/components/icon/assets/app_ems'
import { icon as appFilebeat } from '@elastic/eui/es/components/icon/assets/app_filebeat'
import { icon as appFleet } from '@elastic/eui/es/components/icon/assets/app_fleet'
import { icon as appGis } from '@elastic/eui/es/components/icon/assets/app_gis'
import { icon as appGraph } from '@elastic/eui/es/components/icon/assets/app_graph'
import { icon as appGrok } from '@elastic/eui/es/components/icon/assets/app_grok'
import { icon as appHeartbeat } from '@elastic/eui/es/components/icon/assets/app_heartbeat'
import { icon as appIndexManagement } from '@elastic/eui/es/components/icon/assets/app_index_management'
import { icon as appIndexPattern } from '@elastic/eui/es/components/icon/assets/app_index_pattern'
import { icon as appIndexRollup } from '@elastic/eui/es/components/icon/assets/app_index_rollup'
import { icon as appLens } from '@elastic/eui/es/components/icon/assets/app_lens'
import { icon as appLogs } from '@elastic/eui/es/components/icon/assets/app_logs'
import { icon as appManagement } from '@elastic/eui/es/components/icon/assets/app_management'
import { icon as appMetricbeat } from '@elastic/eui/es/components/icon/assets/app_metricbeat'
import { icon as appMetrics } from '@elastic/eui/es/components/icon/assets/app_metrics'
import { icon as appMl } from '@elastic/eui/es/components/icon/assets/app_ml'
import { icon as appMonitoring } from '@elastic/eui/es/components/icon/assets/app_monitoring'
import { icon as appNotebook } from '@elastic/eui/es/components/icon/assets/app_notebook'
import { icon as appPacketbeat } from '@elastic/eui/es/components/icon/assets/app_packetbeat'
import { icon as appPipeline } from '@elastic/eui/es/components/icon/assets/app_pipeline'
import { icon as appRecentlyViewed } from '@elastic/eui/es/components/icon/assets/app_recently_viewed'
import { icon as appReporting } from '@elastic/eui/es/components/icon/assets/app_reporting'
import { icon as appSavedObjects } from '@elastic/eui/es/components/icon/assets/app_saved_objects'
import { icon as appSearchProfiler } from '@elastic/eui/es/components/icon/assets/app_search_profiler'
import { icon as appSecurity } from '@elastic/eui/es/components/icon/assets/app_security'
import { icon as appSecurityAnalytics } from '@elastic/eui/es/components/icon/assets/app_security_analytics'
import { icon as appSpaces } from '@elastic/eui/es/components/icon/assets/app_spaces'
import { icon as appSql } from '@elastic/eui/es/components/icon/assets/app_sql'
import { icon as appTimelion } from '@elastic/eui/es/components/icon/assets/app_timelion'
import { icon as appUpgradeAssistant } from '@elastic/eui/es/components/icon/assets/app_upgrade_assistant'
import { icon as appUptime } from '@elastic/eui/es/components/icon/assets/app_uptime'
import { icon as appUsersRoles } from '@elastic/eui/es/components/icon/assets/app_users_roles'
import { icon as appVisualize } from '@elastic/eui/es/components/icon/assets/app_visualize'
import { icon as appVulnerabilityManagement } from '@elastic/eui/es/components/icon/assets/app_vulnerability_management'
import { icon as appWatches } from '@elastic/eui/es/components/icon/assets/app_watches'
import { icon as appWorkflows } from '@elastic/eui/es/components/icon/assets/app_workflows'
import { icon as appWorkplaceSearch } from '@elastic/eui/es/components/icon/assets/app_workplace_search'
import { icon as apps } from '@elastic/eui/es/components/icon/assets/apps'
import { icon as arrowEnd } from '@elastic/eui/es/components/icon/assets/arrowEnd'
import { icon as arrowStart } from '@elastic/eui/es/components/icon/assets/arrowStart'
import { icon as arrowDown } from '@elastic/eui/es/components/icon/assets/arrow_down'
import { icon as arrowLeft } from '@elastic/eui/es/components/icon/assets/arrow_left'
import { icon as arrowRight } from '@elastic/eui/es/components/icon/assets/arrow_right'
import { icon as arrowUp } from '@elastic/eui/es/components/icon/assets/arrow_up'
import { icon as article } from '@elastic/eui/es/components/icon/assets/article'
import { icon as asterisk } from '@elastic/eui/es/components/icon/assets/asterisk'
import { icon as at } from '@elastic/eui/es/components/icon/assets/at'
import { icon as backgroundTask } from '@elastic/eui/es/components/icon/assets/background_task'
import { icon as bell } from '@elastic/eui/es/components/icon/assets/bell'
import { icon as bellSlash } from '@elastic/eui/es/components/icon/assets/bellSlash'
import { icon as beta } from '@elastic/eui/es/components/icon/assets/beta'
import { icon as bolt } from '@elastic/eui/es/components/icon/assets/bolt'
import { icon as boxesHorizontal } from '@elastic/eui/es/components/icon/assets/boxes_horizontal'
import { icon as boxesVertical } from '@elastic/eui/es/components/icon/assets/boxes_vertical'
import { icon as branch } from '@elastic/eui/es/components/icon/assets/branch'
import { icon as branchUser } from '@elastic/eui/es/components/icon/assets/branchUser'
import { icon as broom } from '@elastic/eui/es/components/icon/assets/broom'
import { icon as brush } from '@elastic/eui/es/components/icon/assets/brush'
import { icon as bug } from '@elastic/eui/es/components/icon/assets/bug'
import { icon as bullseye } from '@elastic/eui/es/components/icon/assets/bullseye'
import { icon as calendar } from '@elastic/eui/es/components/icon/assets/calendar'
import { icon as changePointDetection } from '@elastic/eui/es/components/icon/assets/change_point_detection'
import { icon as check } from '@elastic/eui/es/components/icon/assets/check'
import { icon as checkCircle } from '@elastic/eui/es/components/icon/assets/checkCircle'
import { icon as checkInCircleFilled } from '@elastic/eui/es/components/icon/assets/checkInCircleFilled'
import { icon as cheer } from '@elastic/eui/es/components/icon/assets/cheer'
import { icon as clickLeft } from '@elastic/eui/es/components/icon/assets/clickLeft'
import { icon as clickRight } from '@elastic/eui/es/components/icon/assets/clickRight'
import { icon as clock } from '@elastic/eui/es/components/icon/assets/clock'
import { icon as clockCounter } from '@elastic/eui/es/components/icon/assets/clockCounter'
import { icon as cloudDrizzle } from '@elastic/eui/es/components/icon/assets/cloudDrizzle'
import { icon as cloudStormy } from '@elastic/eui/es/components/icon/assets/cloudStormy'
import { icon as cloudSunny } from '@elastic/eui/es/components/icon/assets/cloudSunny'
import { icon as cluster } from '@elastic/eui/es/components/icon/assets/cluster'
import { icon as code } from '@elastic/eui/es/components/icon/assets/code'
import { icon as color } from '@elastic/eui/es/components/icon/assets/color'
import { icon as comment } from '@elastic/eui/es/components/icon/assets/comment'
import { icon as compute } from '@elastic/eui/es/components/icon/assets/compute'
import { icon as console } from '@elastic/eui/es/components/icon/assets/console'
import { icon as container } from '@elastic/eui/es/components/icon/assets/container'
import { icon as continuityAbove } from '@elastic/eui/es/components/icon/assets/continuityAbove'
import { icon as continuityAboveBelow } from '@elastic/eui/es/components/icon/assets/continuityAboveBelow'
import { icon as continuityBelow } from '@elastic/eui/es/components/icon/assets/continuityBelow'
import { icon as continuityWithin } from '@elastic/eui/es/components/icon/assets/continuityWithin'
import { icon as contrast } from '@elastic/eui/es/components/icon/assets/contrast'
import { icon as contrastHigh } from '@elastic/eui/es/components/icon/assets/contrastHigh'
import { icon as controls } from '@elastic/eui/es/components/icon/assets/controls'
import { icon as copy } from '@elastic/eui/es/components/icon/assets/copy'
import { icon as copyClipboard } from '@elastic/eui/es/components/icon/assets/copy_clipboard'
import { icon as cross } from '@elastic/eui/es/components/icon/assets/cross'
import { icon as crossInCircle } from '@elastic/eui/es/components/icon/assets/crossInCircle'
import { icon as crossInCircle1 } from '@elastic/eui/es/components/icon/assets/cross_in_circle'
import { icon as crosshairs } from '@elastic/eui/es/components/icon/assets/crosshairs'
import { icon as currency } from '@elastic/eui/es/components/icon/assets/currency'
import { icon as cut } from '@elastic/eui/es/components/icon/assets/cut'
import { icon as database } from '@elastic/eui/es/components/icon/assets/database'
import { icon as desktop } from '@elastic/eui/es/components/icon/assets/desktop'
import { icon as diff } from '@elastic/eui/es/components/icon/assets/diff'
import { icon as document } from '@elastic/eui/es/components/icon/assets/document'
import { icon as documentEdit } from '@elastic/eui/es/components/icon/assets/documentEdit'
import { icon as documentation } from '@elastic/eui/es/components/icon/assets/documentation'
import { icon as documents } from '@elastic/eui/es/components/icon/assets/documents'
import { icon as dot } from '@elastic/eui/es/components/icon/assets/dot'
import { icon as dotInCircle } from '@elastic/eui/es/components/icon/assets/dotInCircle'
import { icon as doubleArrowLeft } from '@elastic/eui/es/components/icon/assets/doubleArrowLeft'
import { icon as doubleArrowRight } from '@elastic/eui/es/components/icon/assets/doubleArrowRight'
import { icon as download } from '@elastic/eui/es/components/icon/assets/download'
import { icon as editorDistributeHorizontal } from '@elastic/eui/es/components/icon/assets/editorDistributeHorizontal'
import { icon as editorDistributeVertical } from '@elastic/eui/es/components/icon/assets/editorDistributeVertical'
import { icon as editorItemAlignBottom } from '@elastic/eui/es/components/icon/assets/editorItemAlignBottom'
import { icon as editorItemAlignCenter } from '@elastic/eui/es/components/icon/assets/editorItemAlignCenter'
import { icon as editorItemAlignLeft } from '@elastic/eui/es/components/icon/assets/editorItemAlignLeft'
import { icon as editorItemAlignMiddle } from '@elastic/eui/es/components/icon/assets/editorItemAlignMiddle'
import { icon as editorItemAlignRight } from '@elastic/eui/es/components/icon/assets/editorItemAlignRight'
import { icon as editorItemAlignTop } from '@elastic/eui/es/components/icon/assets/editorItemAlignTop'
import { icon as editorPositionBottomLeft } from '@elastic/eui/es/components/icon/assets/editorPositionBottomLeft'
import { icon as editorPositionBottomRight } from '@elastic/eui/es/components/icon/assets/editorPositionBottomRight'
import { icon as editorPositionTopLeft } from '@elastic/eui/es/components/icon/assets/editorPositionTopLeft'
import { icon as editorPositionTopRight } from '@elastic/eui/es/components/icon/assets/editorPositionTopRight'
import { icon as editorAlignCenter } from '@elastic/eui/es/components/icon/assets/editor_align_center'
import { icon as editorAlignLeft } from '@elastic/eui/es/components/icon/assets/editor_align_left'
import { icon as editorAlignRight } from '@elastic/eui/es/components/icon/assets/editor_align_right'
import { icon as editorBold } from '@elastic/eui/es/components/icon/assets/editor_bold'
import { icon as editorChecklist } from '@elastic/eui/es/components/icon/assets/editor_checklist'
import { icon as editorHeading } from '@elastic/eui/es/components/icon/assets/editor_heading'
import { icon as editorItalic } from '@elastic/eui/es/components/icon/assets/editor_italic'
import { icon as editorLink } from '@elastic/eui/es/components/icon/assets/editor_link'
import { icon as editorOrderedList } from '@elastic/eui/es/components/icon/assets/editor_ordered_list'
import { icon as editorRedo } from '@elastic/eui/es/components/icon/assets/editor_redo'
import { icon as editorStrike } from '@elastic/eui/es/components/icon/assets/editor_strike'
import { icon as editorTable } from '@elastic/eui/es/components/icon/assets/editor_table'
import { icon as editorUnderline } from '@elastic/eui/es/components/icon/assets/editor_underline'
import { icon as editorUndo } from '@elastic/eui/es/components/icon/assets/editor_undo'
import { icon as editorUnorderedList } from '@elastic/eui/es/components/icon/assets/editor_unordered_list'
import { icon as email } from '@elastic/eui/es/components/icon/assets/email'
import { icon as empty } from '@elastic/eui/es/components/icon/assets/empty'
import { icon as endpoint } from '@elastic/eui/es/components/icon/assets/endpoint'
import { icon as eql } from '@elastic/eui/es/components/icon/assets/eql'
import { icon as eraser } from '@elastic/eui/es/components/icon/assets/eraser'
import { icon as error } from '@elastic/eui/es/components/icon/assets/error'
import { icon as errorFilled } from '@elastic/eui/es/components/icon/assets/errorFilled'
import { icon as esqlVis } from '@elastic/eui/es/components/icon/assets/esqlVis'
import { icon as exit } from '@elastic/eui/es/components/icon/assets/exit'
import { icon as expand } from '@elastic/eui/es/components/icon/assets/expand'
import { icon as expandMini } from '@elastic/eui/es/components/icon/assets/expandMini'
import { icon as exportIcon } from '@elastic/eui/es/components/icon/assets/export'
import { icon as eye } from '@elastic/eui/es/components/icon/assets/eye'
import { icon as eyeClosed } from '@elastic/eui/es/components/icon/assets/eye_closed'
import { icon as faceHappy } from '@elastic/eui/es/components/icon/assets/face_happy'
import { icon as faceNeutral } from '@elastic/eui/es/components/icon/assets/face_neutral'
import { icon as faceSad } from '@elastic/eui/es/components/icon/assets/face_sad'
import { icon as fieldStatistics } from '@elastic/eui/es/components/icon/assets/field_statistics'
import { icon as filter } from '@elastic/eui/es/components/icon/assets/filter'
import { icon as filterExclude } from '@elastic/eui/es/components/icon/assets/filterExclude'
import { icon as filterIgnore } from '@elastic/eui/es/components/icon/assets/filterIgnore'
import { icon as filterInCircle } from '@elastic/eui/es/components/icon/assets/filterInCircle'
import { icon as filterInclude } from '@elastic/eui/es/components/icon/assets/filterInclude'
import { icon as flag } from '@elastic/eui/es/components/icon/assets/flag'
import { icon as flask } from '@elastic/eui/es/components/icon/assets/flask'
import { icon as fold } from '@elastic/eui/es/components/icon/assets/fold'
import { icon as folderCheck } from '@elastic/eui/es/components/icon/assets/folder_check'
import { icon as folderClosed } from '@elastic/eui/es/components/icon/assets/folder_closed'
import { icon as folderExclamation } from '@elastic/eui/es/components/icon/assets/folder_exclamation'
import { icon as folderOpen } from '@elastic/eui/es/components/icon/assets/folder_open'
import { icon as frameNext } from '@elastic/eui/es/components/icon/assets/frameNext'
import { icon as framePrevious } from '@elastic/eui/es/components/icon/assets/framePrevious'
import { icon as fullScreenExit } from '@elastic/eui/es/components/icon/assets/fullScreenExit'
import { icon as fullScreen } from '@elastic/eui/es/components/icon/assets/full_screen'
import { icon as functionIcon } from '@elastic/eui/es/components/icon/assets/function'
import { icon as gear } from '@elastic/eui/es/components/icon/assets/gear'
import { icon as globe } from '@elastic/eui/es/components/icon/assets/globe'
import { icon as grab } from '@elastic/eui/es/components/icon/assets/grab'
import { icon as grabOmnidirectional } from '@elastic/eui/es/components/icon/assets/grabOmnidirectional'
import { icon as grabHorizontal } from '@elastic/eui/es/components/icon/assets/grab_horizontal'
import { icon as gradient } from '@elastic/eui/es/components/icon/assets/gradient'
import { icon as grid } from '@elastic/eui/es/components/icon/assets/grid'
import { icon as heart } from '@elastic/eui/es/components/icon/assets/heart'
import { icon as heatmap } from '@elastic/eui/es/components/icon/assets/heatmap'
import { icon as help } from '@elastic/eui/es/components/icon/assets/help'
import { icon as home } from '@elastic/eui/es/components/icon/assets/home'
import { icon as image } from '@elastic/eui/es/components/icon/assets/image'
import { icon as importIcon } from '@elastic/eui/es/components/icon/assets/import'
import { icon as index } from '@elastic/eui/es/components/icon/assets/index'
import { icon as indexTemporary } from '@elastic/eui/es/components/icon/assets/indexTemporary'
import { icon as indexClose } from '@elastic/eui/es/components/icon/assets/index_close'
import { icon as indexEdit } from '@elastic/eui/es/components/icon/assets/index_edit'
import { icon as indexFlush } from '@elastic/eui/es/components/icon/assets/index_flush'
import { icon as indexMapping } from '@elastic/eui/es/components/icon/assets/index_mapping'
import { icon as indexOpen } from '@elastic/eui/es/components/icon/assets/index_open'
import { icon as indexRuntime } from '@elastic/eui/es/components/icon/assets/index_runtime'
import { icon as indexSettings } from '@elastic/eui/es/components/icon/assets/index_settings'
import { icon as infinity } from '@elastic/eui/es/components/icon/assets/infinity'
import { icon as info } from '@elastic/eui/es/components/icon/assets/info'
import { icon as inputOutput } from '@elastic/eui/es/components/icon/assets/inputOutput'
import { icon as inspect } from '@elastic/eui/es/components/icon/assets/inspect'
import { icon as invert } from '@elastic/eui/es/components/icon/assets/invert'
import { icon as ip } from '@elastic/eui/es/components/icon/assets/ip'
import { icon as issue } from '@elastic/eui/es/components/icon/assets/issue'
import { icon as key } from '@elastic/eui/es/components/icon/assets/key'
import { icon as keyboard } from '@elastic/eui/es/components/icon/assets/keyboard'
import { icon as kqlField } from '@elastic/eui/es/components/icon/assets/kql_field'
import { icon as kqlFunction } from '@elastic/eui/es/components/icon/assets/kql_function'
import { icon as kqlOperand } from '@elastic/eui/es/components/icon/assets/kql_operand'
import { icon as kqlSelector } from '@elastic/eui/es/components/icon/assets/kql_selector'
import { icon as kqlValue } from '@elastic/eui/es/components/icon/assets/kql_value'
import { icon as kubernetesNode } from '@elastic/eui/es/components/icon/assets/kubernetesNode'
import { icon as kubernetesPod } from '@elastic/eui/es/components/icon/assets/kubernetesPod'
import { icon as launch } from '@elastic/eui/es/components/icon/assets/launch'
import { icon as layers } from '@elastic/eui/es/components/icon/assets/layers'
import { icon as lettering } from '@elastic/eui/es/components/icon/assets/lettering'
import { icon as lineDashed } from '@elastic/eui/es/components/icon/assets/lineDashed'
import { icon as lineDotted } from '@elastic/eui/es/components/icon/assets/lineDotted'
import { icon as lineSolid } from '@elastic/eui/es/components/icon/assets/lineSolid'
import { icon as link } from '@elastic/eui/es/components/icon/assets/link'
import { icon as list } from '@elastic/eui/es/components/icon/assets/list'
import { icon as listAdd } from '@elastic/eui/es/components/icon/assets/list_add'
import { icon as lock } from '@elastic/eui/es/components/icon/assets/lock'
import { icon as lockOpen } from '@elastic/eui/es/components/icon/assets/lockOpen'
import { icon as logPatternAnalysis } from '@elastic/eui/es/components/icon/assets/log_pattern_analysis'
import { icon as logRateAnalysis } from '@elastic/eui/es/components/icon/assets/log_rate_analysis'
import { icon as logoAerospike } from '@elastic/eui/es/components/icon/assets/logo_aerospike'
import { icon as logoApache } from '@elastic/eui/es/components/icon/assets/logo_apache'
import { icon as logoAppSearch } from '@elastic/eui/es/components/icon/assets/logo_app_search'
import { icon as logoAws } from '@elastic/eui/es/components/icon/assets/logo_aws'
import { icon as logoAwsMono } from '@elastic/eui/es/components/icon/assets/logo_aws_mono'
import { icon as logoAzure } from '@elastic/eui/es/components/icon/assets/logo_azure'
import { icon as logoAzureMono } from '@elastic/eui/es/components/icon/assets/logo_azure_mono'
import { icon as logoBeats } from '@elastic/eui/es/components/icon/assets/logo_beats'
import { icon as logoBusinessAnalytics } from '@elastic/eui/es/components/icon/assets/logo_business_analytics'
import { icon as logoCeph } from '@elastic/eui/es/components/icon/assets/logo_ceph'
import { icon as logoCloud } from '@elastic/eui/es/components/icon/assets/logo_cloud'
import { icon as logoCloudEce } from '@elastic/eui/es/components/icon/assets/logo_cloud_ece'
import { icon as logoCode } from '@elastic/eui/es/components/icon/assets/logo_code'
import { icon as logoCodesandbox } from '@elastic/eui/es/components/icon/assets/logo_codesandbox'
import { icon as logoCouchbase } from '@elastic/eui/es/components/icon/assets/logo_couchbase'
import { icon as logoDocker } from '@elastic/eui/es/components/icon/assets/logo_docker'
import { icon as logoDropwizard } from '@elastic/eui/es/components/icon/assets/logo_dropwizard'
import { icon as logoElastic } from '@elastic/eui/es/components/icon/assets/logo_elastic'
import { icon as logoElasticStack } from '@elastic/eui/es/components/icon/assets/logo_elastic_stack'
import { icon as logoElasticsearch } from '@elastic/eui/es/components/icon/assets/logo_elasticsearch'
import { icon as logoEnterpriseSearch } from '@elastic/eui/es/components/icon/assets/logo_enterprise_search'
import { icon as logoEtcd } from '@elastic/eui/es/components/icon/assets/logo_etcd'
import { icon as logoGcp } from '@elastic/eui/es/components/icon/assets/logo_gcp'
import { icon as logoGcpMono } from '@elastic/eui/es/components/icon/assets/logo_gcp_mono'
import { icon as logoGithub } from '@elastic/eui/es/components/icon/assets/logo_github'
import { icon as logoGmail } from '@elastic/eui/es/components/icon/assets/logo_gmail'
import { icon as logoGolang } from '@elastic/eui/es/components/icon/assets/logo_golang'
import { icon as logoGoogleG } from '@elastic/eui/es/components/icon/assets/logo_google_g'
import { icon as logoHaproxy } from '@elastic/eui/es/components/icon/assets/logo_haproxy'
import { icon as logoIbm } from '@elastic/eui/es/components/icon/assets/logo_ibm'
import { icon as logoIbmMono } from '@elastic/eui/es/components/icon/assets/logo_ibm_mono'
import { icon as logoKafka } from '@elastic/eui/es/components/icon/assets/logo_kafka'
import { icon as logoKibana } from '@elastic/eui/es/components/icon/assets/logo_kibana'
import { icon as logoKubernetes } from '@elastic/eui/es/components/icon/assets/logo_kubernetes'
import { icon as logoLogging } from '@elastic/eui/es/components/icon/assets/logo_logging'
import { icon as logoLogstash } from '@elastic/eui/es/components/icon/assets/logo_logstash'
import { icon as logoMaps } from '@elastic/eui/es/components/icon/assets/logo_maps'
import { icon as logoMemcached } from '@elastic/eui/es/components/icon/assets/logo_memcached'
import { icon as logoMetrics } from '@elastic/eui/es/components/icon/assets/logo_metrics'
import { icon as logoMongodb } from '@elastic/eui/es/components/icon/assets/logo_mongodb'
import { icon as logoMysql } from '@elastic/eui/es/components/icon/assets/logo_mysql'
import { icon as logoNginx } from '@elastic/eui/es/components/icon/assets/logo_nginx'
import { icon as logoObservability } from '@elastic/eui/es/components/icon/assets/logo_observability'
import { icon as logoOsquery } from '@elastic/eui/es/components/icon/assets/logo_osquery'
import { icon as logoPhp } from '@elastic/eui/es/components/icon/assets/logo_php'
import { icon as logoPostgres } from '@elastic/eui/es/components/icon/assets/logo_postgres'
import { icon as logoPrometheus } from '@elastic/eui/es/components/icon/assets/logo_prometheus'
import { icon as logoRabbitmq } from '@elastic/eui/es/components/icon/assets/logo_rabbitmq'
import { icon as logoRedis } from '@elastic/eui/es/components/icon/assets/logo_redis'
import { icon as logoSecurity } from '@elastic/eui/es/components/icon/assets/logo_security'
import { icon as logoSiteSearch } from '@elastic/eui/es/components/icon/assets/logo_site_search'
import { icon as logoSketch } from '@elastic/eui/es/components/icon/assets/logo_sketch'
import { icon as logoSlack } from '@elastic/eui/es/components/icon/assets/logo_slack'
import { icon as logoUptime } from '@elastic/eui/es/components/icon/assets/logo_uptime'
import { icon as logoVulnerabilityManagement } from '@elastic/eui/es/components/icon/assets/logo_vulnerability_management'
import { icon as logoWebhook } from '@elastic/eui/es/components/icon/assets/logo_webhook'
import { icon as logoWindows } from '@elastic/eui/es/components/icon/assets/logo_windows'
import { icon as logoWorkplaceSearch } from '@elastic/eui/es/components/icon/assets/logo_workplace_search'
import { icon as logstashFilter } from '@elastic/eui/es/components/icon/assets/logstash_filter'
import { icon as logstashIf } from '@elastic/eui/es/components/icon/assets/logstash_if'
import { icon as logstashInput } from '@elastic/eui/es/components/icon/assets/logstash_input'
import { icon as logstashOutput } from '@elastic/eui/es/components/icon/assets/logstash_output'
import { icon as logstashQueue } from '@elastic/eui/es/components/icon/assets/logstash_queue'
import { icon as magnet } from '@elastic/eui/es/components/icon/assets/magnet'
import { icon as magnifyWithExclamation } from '@elastic/eui/es/components/icon/assets/magnifyWithExclamation'
import { icon as magnifyWithMinus } from '@elastic/eui/es/components/icon/assets/magnifyWithMinus'
import { icon as magnifyWithPlus } from '@elastic/eui/es/components/icon/assets/magnifyWithPlus'
import { icon as mapMarker } from '@elastic/eui/es/components/icon/assets/map_marker'
import { icon as memory } from '@elastic/eui/es/components/icon/assets/memory'
import { icon as menu } from '@elastic/eui/es/components/icon/assets/menu'
import { icon as menuDown } from '@elastic/eui/es/components/icon/assets/menuDown'
import { icon as menuLeft } from '@elastic/eui/es/components/icon/assets/menuLeft'
import { icon as menuRight } from '@elastic/eui/es/components/icon/assets/menuRight'
import { icon as menuUp } from '@elastic/eui/es/components/icon/assets/menuUp'
import { icon as merge } from '@elastic/eui/es/components/icon/assets/merge'
import { icon as minimize } from '@elastic/eui/es/components/icon/assets/minimize'
import { icon as minus } from '@elastic/eui/es/components/icon/assets/minus'
import { icon as minusInCircle } from '@elastic/eui/es/components/icon/assets/minus_in_circle'
import { icon as minusInCircleFilled } from '@elastic/eui/es/components/icon/assets/minus_in_circle_filled'
import { icon as minusInSquare } from '@elastic/eui/es/components/icon/assets/minus_in_square'
import { icon as mlClassificationJob } from '@elastic/eui/es/components/icon/assets/ml_classification_job'
import { icon as mlCreateAdvancedJob } from '@elastic/eui/es/components/icon/assets/ml_create_advanced_job'
import { icon as mlCreateGenericJob } from '@elastic/eui/es/components/icon/assets/ml_create_generic_job'
import { icon as mlCreateGeoJob } from '@elastic/eui/es/components/icon/assets/ml_create_geo_job'
import { icon as mlCreateMultiMetricJob } from '@elastic/eui/es/components/icon/assets/ml_create_multi_metric_job'
import { icon as mlCreatePopulationJob } from '@elastic/eui/es/components/icon/assets/ml_create_population_job'
import { icon as mlCreateSingleMetricJob } from '@elastic/eui/es/components/icon/assets/ml_create_single_metric_job'
import { icon as mlDataVisualizer } from '@elastic/eui/es/components/icon/assets/ml_data_visualizer'
import { icon as mlOutlierDetectionJob } from '@elastic/eui/es/components/icon/assets/ml_outlier_detection_job'
import { icon as mlRegressionJob } from '@elastic/eui/es/components/icon/assets/ml_regression_job'
import { icon as mobile } from '@elastic/eui/es/components/icon/assets/mobile'
import { icon as moon } from '@elastic/eui/es/components/icon/assets/moon'
import { icon as move } from '@elastic/eui/es/components/icon/assets/move'
import { icon as namespace } from '@elastic/eui/es/components/icon/assets/namespace'
import { icon as nested } from '@elastic/eui/es/components/icon/assets/nested'
import { icon as newChat } from '@elastic/eui/es/components/icon/assets/new_chat'
import { icon as node } from '@elastic/eui/es/components/icon/assets/node'
import { icon as number } from '@elastic/eui/es/components/icon/assets/number'
import { icon as offline } from '@elastic/eui/es/components/icon/assets/offline'
import { icon as online } from '@elastic/eui/es/components/icon/assets/online'
import { icon as packageIcon } from '@elastic/eui/es/components/icon/assets/package'
import { icon as pageSelect } from '@elastic/eui/es/components/icon/assets/pageSelect'
import { icon as pagesSelect } from '@elastic/eui/es/components/icon/assets/pagesSelect'
import { icon as paint } from '@elastic/eui/es/components/icon/assets/paint'
import { icon as palette } from '@elastic/eui/es/components/icon/assets/palette'
import { icon as paperClip } from '@elastic/eui/es/components/icon/assets/paper_clip'
import { icon as partial } from '@elastic/eui/es/components/icon/assets/partial'
import { icon as pause } from '@elastic/eui/es/components/icon/assets/pause'
import { icon as payment } from '@elastic/eui/es/components/icon/assets/payment'
import { icon as pencil } from '@elastic/eui/es/components/icon/assets/pencil'
import { icon as percent } from '@elastic/eui/es/components/icon/assets/percent'
import { icon as pin } from '@elastic/eui/es/components/icon/assets/pin'
import { icon as pinFilled } from '@elastic/eui/es/components/icon/assets/pin_filled'
import { icon as pipeBreaks } from '@elastic/eui/es/components/icon/assets/pipeBreaks'
import { icon as pipeNoBreaks } from '@elastic/eui/es/components/icon/assets/pipeNoBreaks'
import { icon as pivot } from '@elastic/eui/es/components/icon/assets/pivot'
import { icon as play } from '@elastic/eui/es/components/icon/assets/play'
import { icon as playFilled } from '@elastic/eui/es/components/icon/assets/playFilled'
import { icon as plugs } from '@elastic/eui/es/components/icon/assets/plugs'
import { icon as plus } from '@elastic/eui/es/components/icon/assets/plus'
import { icon as plusInCircle } from '@elastic/eui/es/components/icon/assets/plus_in_circle'
import { icon as plusInCircleFilled } from '@elastic/eui/es/components/icon/assets/plus_in_circle_filled'
import { icon as plusInSquare } from '@elastic/eui/es/components/icon/assets/plus_in_square'
import { icon as popout } from '@elastic/eui/es/components/icon/assets/popout'
import { icon as push } from '@elastic/eui/es/components/icon/assets/push'
import { icon as question } from '@elastic/eui/es/components/icon/assets/question'
import { icon as quote } from '@elastic/eui/es/components/icon/assets/quote'
import { icon as readOnly } from '@elastic/eui/es/components/icon/assets/readOnly'
import { icon as refresh } from '@elastic/eui/es/components/icon/assets/refresh'
import { icon as reporter } from '@elastic/eui/es/components/icon/assets/reporter'
import { icon as returnKey } from '@elastic/eui/es/components/icon/assets/return_key'
import { icon as save } from '@elastic/eui/es/components/icon/assets/save'
import { icon as scale } from '@elastic/eui/es/components/icon/assets/scale'
import { icon as search } from '@elastic/eui/es/components/icon/assets/search'
import { icon as section } from '@elastic/eui/es/components/icon/assets/section'
import { icon as securitySignal } from '@elastic/eui/es/components/icon/assets/securitySignal'
import { icon as securitySignalDetected } from '@elastic/eui/es/components/icon/assets/securitySignalDetected'
import { icon as securitySignalResolved } from '@elastic/eui/es/components/icon/assets/securitySignalResolved'
import { icon as sessionViewer } from '@elastic/eui/es/components/icon/assets/sessionViewer'
import { icon as shard } from '@elastic/eui/es/components/icon/assets/shard'
import { icon as share } from '@elastic/eui/es/components/icon/assets/share'
import { icon as singleMetricViewer } from '@elastic/eui/es/components/icon/assets/single_metric_viewer'
import { icon as snowflake } from '@elastic/eui/es/components/icon/assets/snowflake'
import { icon as sortAscending } from '@elastic/eui/es/components/icon/assets/sortAscending'
import { icon as sortDescending } from '@elastic/eui/es/components/icon/assets/sortDescending'
import { icon as sortLeft } from '@elastic/eui/es/components/icon/assets/sortLeft'
import { icon as sortRight } from '@elastic/eui/es/components/icon/assets/sortRight'
import { icon as sortDown } from '@elastic/eui/es/components/icon/assets/sort_down'
import { icon as sortUp } from '@elastic/eui/es/components/icon/assets/sort_up'
import { icon as sortable } from '@elastic/eui/es/components/icon/assets/sortable'
import { icon as spaces } from '@elastic/eui/es/components/icon/assets/spaces'
import { icon as sparkles } from '@elastic/eui/es/components/icon/assets/sparkles'
import { icon as starPlusEmpty } from '@elastic/eui/es/components/icon/assets/starPlusEmpty'
import { icon as starPlusFilled } from '@elastic/eui/es/components/icon/assets/starPlusFilled'
import { icon as starEmpty } from '@elastic/eui/es/components/icon/assets/star_empty'
import { icon as starEmptySpace } from '@elastic/eui/es/components/icon/assets/star_empty_space'
import { icon as starFilled } from '@elastic/eui/es/components/icon/assets/star_filled'
import { icon as starFilledSpace } from '@elastic/eui/es/components/icon/assets/star_filled_space'
import { icon as starMinusEmpty } from '@elastic/eui/es/components/icon/assets/star_minus_empty'
import { icon as starMinusFilled } from '@elastic/eui/es/components/icon/assets/star_minus_filled'
import { icon as stats } from '@elastic/eui/es/components/icon/assets/stats'
import { icon as stop } from '@elastic/eui/es/components/icon/assets/stop'
import { icon as stopFilled } from '@elastic/eui/es/components/icon/assets/stop_filled'
import { icon as stopSlash } from '@elastic/eui/es/components/icon/assets/stop_slash'
import { icon as storage } from '@elastic/eui/es/components/icon/assets/storage'
import { icon as streamsClassic } from '@elastic/eui/es/components/icon/assets/streams_classic'
import { icon as streamsWired } from '@elastic/eui/es/components/icon/assets/streams_wired'
import { icon as string } from '@elastic/eui/es/components/icon/assets/string'
import { icon as submodule } from '@elastic/eui/es/components/icon/assets/submodule'
import { icon as sun } from '@elastic/eui/es/components/icon/assets/sun'
import { icon as swatchInput } from '@elastic/eui/es/components/icon/assets/swatch_input'
import { icon as symlink } from '@elastic/eui/es/components/icon/assets/symlink'
import { icon as tableOfContents } from '@elastic/eui/es/components/icon/assets/tableOfContents'
import { icon as tableDensityCompact } from '@elastic/eui/es/components/icon/assets/table_density_compact'
import { icon as tableDensityExpanded } from '@elastic/eui/es/components/icon/assets/table_density_expanded'
import { icon as tableDensityNormal } from '@elastic/eui/es/components/icon/assets/table_density_normal'
import { icon as tag } from '@elastic/eui/es/components/icon/assets/tag'
import { icon as tear } from '@elastic/eui/es/components/icon/assets/tear'
import { icon as temperature } from '@elastic/eui/es/components/icon/assets/temperature'
import { icon as thumbDown } from '@elastic/eui/es/components/icon/assets/thumbDown'
import { icon as thumbUp } from '@elastic/eui/es/components/icon/assets/thumbUp'
import { icon as timeRefresh } from '@elastic/eui/es/components/icon/assets/timeRefresh'
import { icon as timeline } from '@elastic/eui/es/components/icon/assets/timeline'
import { icon as timelineWithArrow } from '@elastic/eui/es/components/icon/assets/timelineWithArrow'
import { icon as timeslider } from '@elastic/eui/es/components/icon/assets/timeslider'
import { icon as tokenAlias } from '@elastic/eui/es/components/icon/assets/tokenAlias'
import { icon as tokenAnnotation } from '@elastic/eui/es/components/icon/assets/tokenAnnotation'
import { icon as tokenArray } from '@elastic/eui/es/components/icon/assets/tokenArray'
import { icon as tokenBinary } from '@elastic/eui/es/components/icon/assets/tokenBinary'
import { icon as tokenBoolean } from '@elastic/eui/es/components/icon/assets/tokenBoolean'
import { icon as tokenClass } from '@elastic/eui/es/components/icon/assets/tokenClass'
import { icon as tokenCompletionSuggester } from '@elastic/eui/es/components/icon/assets/tokenCompletionSuggester'
import { icon as tokenConstant } from '@elastic/eui/es/components/icon/assets/tokenConstant'
import { icon as tokenDate } from '@elastic/eui/es/components/icon/assets/tokenDate'
import { icon as tokenDimension } from '@elastic/eui/es/components/icon/assets/tokenDimension'
import { icon as tokenElement } from '@elastic/eui/es/components/icon/assets/tokenElement'
import { icon as tokenEnum } from '@elastic/eui/es/components/icon/assets/tokenEnum'
import { icon as tokenEnumMember } from '@elastic/eui/es/components/icon/assets/tokenEnumMember'
import { icon as tokenEvent } from '@elastic/eui/es/components/icon/assets/tokenEvent'
import { icon as tokenException } from '@elastic/eui/es/components/icon/assets/tokenException'
import { icon as tokenField } from '@elastic/eui/es/components/icon/assets/tokenField'
import { icon as tokenFile } from '@elastic/eui/es/components/icon/assets/tokenFile'
import { icon as tokenFlattened } from '@elastic/eui/es/components/icon/assets/tokenFlattened'
import { icon as tokenFunction } from '@elastic/eui/es/components/icon/assets/tokenFunction'
import { icon as tokenGeo } from '@elastic/eui/es/components/icon/assets/tokenGeo'
import { icon as tokenHistogram } from '@elastic/eui/es/components/icon/assets/tokenHistogram'
import { icon as tokenIP } from '@elastic/eui/es/components/icon/assets/tokenIP'
import { icon as tokenInterface } from '@elastic/eui/es/components/icon/assets/tokenInterface'
import { icon as tokenJoin } from '@elastic/eui/es/components/icon/assets/tokenJoin'
import { icon as tokenKey } from '@elastic/eui/es/components/icon/assets/tokenKey'
import { icon as tokenKeyword } from '@elastic/eui/es/components/icon/assets/tokenKeyword'
import { icon as tokenMethod } from '@elastic/eui/es/components/icon/assets/tokenMethod'
import { icon as tokenMetricCounter } from '@elastic/eui/es/components/icon/assets/tokenMetricCounter'
import { icon as tokenMetricGauge } from '@elastic/eui/es/components/icon/assets/tokenMetricGauge'
import { icon as tokenModule } from '@elastic/eui/es/components/icon/assets/tokenModule'
import { icon as tokenNamespace } from '@elastic/eui/es/components/icon/assets/tokenNamespace'
import { icon as tokenNested } from '@elastic/eui/es/components/icon/assets/tokenNested'
import { icon as tokenNull } from '@elastic/eui/es/components/icon/assets/tokenNull'
import { icon as tokenNumber } from '@elastic/eui/es/components/icon/assets/tokenNumber'
import { icon as tokenObject } from '@elastic/eui/es/components/icon/assets/tokenObject'
import { icon as tokenOperator } from '@elastic/eui/es/components/icon/assets/tokenOperator'
import { icon as tokenPackage } from '@elastic/eui/es/components/icon/assets/tokenPackage'
import { icon as tokenParameter } from '@elastic/eui/es/components/icon/assets/tokenParameter'
import { icon as tokenPercolator } from '@elastic/eui/es/components/icon/assets/tokenPercolator'
import { icon as tokenProperty } from '@elastic/eui/es/components/icon/assets/tokenProperty'
import { icon as tokenRange } from '@elastic/eui/es/components/icon/assets/tokenRange'
import { icon as tokenRankFeature } from '@elastic/eui/es/components/icon/assets/tokenRankFeature'
import { icon as tokenRankFeatures } from '@elastic/eui/es/components/icon/assets/tokenRankFeatures'
import { icon as tokenRepo } from '@elastic/eui/es/components/icon/assets/tokenRepo'
import { icon as tokenSearchType } from '@elastic/eui/es/components/icon/assets/tokenSearchType'
import { icon as tokenSemanticText } from '@elastic/eui/es/components/icon/assets/tokenSemanticText'
import { icon as tokenShape } from '@elastic/eui/es/components/icon/assets/tokenShape'
import { icon as tokenString } from '@elastic/eui/es/components/icon/assets/tokenString'
import { icon as tokenStruct } from '@elastic/eui/es/components/icon/assets/tokenStruct'
import { icon as tokenSymbol } from '@elastic/eui/es/components/icon/assets/tokenSymbol'
import { icon as tokenTag } from '@elastic/eui/es/components/icon/assets/tokenTag'
import { icon as tokenText } from '@elastic/eui/es/components/icon/assets/tokenText'
import { icon as tokenTokenCount } from '@elastic/eui/es/components/icon/assets/tokenTokenCount'
import { icon as tokenVariable } from '@elastic/eui/es/components/icon/assets/tokenVariable'
import { icon as tokenVectorDense } from '@elastic/eui/es/components/icon/assets/tokenVectorDense'
import { icon as tokenVectorSparse } from '@elastic/eui/es/components/icon/assets/tokenVectorSparse'
import { icon as training } from '@elastic/eui/es/components/icon/assets/training'
import { icon as transitionLeftIn } from '@elastic/eui/es/components/icon/assets/transitionLeftIn'
import { icon as transitionLeftOut } from '@elastic/eui/es/components/icon/assets/transitionLeftOut'
import { icon as transitionTopIn } from '@elastic/eui/es/components/icon/assets/transitionTopIn'
import { icon as transitionTopOut } from '@elastic/eui/es/components/icon/assets/transitionTopOut'
import { icon as trash } from '@elastic/eui/es/components/icon/assets/trash'
import { icon as unfold } from '@elastic/eui/es/components/icon/assets/unfold'
import { icon as unlink } from '@elastic/eui/es/components/icon/assets/unlink'
import { icon as user } from '@elastic/eui/es/components/icon/assets/user'
import { icon as users } from '@elastic/eui/es/components/icon/assets/users'
import { icon as vector } from '@elastic/eui/es/components/icon/assets/vector'
import { icon as videoPlayer } from '@elastic/eui/es/components/icon/assets/videoPlayer'
import { icon as visArea } from '@elastic/eui/es/components/icon/assets/vis_area'
import { icon as visAreaStacked } from '@elastic/eui/es/components/icon/assets/vis_area_stacked'
import { icon as visBarHorizontal } from '@elastic/eui/es/components/icon/assets/vis_bar_horizontal'
import { icon as visBarHorizontalStacked } from '@elastic/eui/es/components/icon/assets/vis_bar_horizontal_stacked'
import { icon as visBarVertical } from '@elastic/eui/es/components/icon/assets/vis_bar_vertical'
import { icon as visBarVerticalStacked } from '@elastic/eui/es/components/icon/assets/vis_bar_vertical_stacked'
import { icon as visGauge } from '@elastic/eui/es/components/icon/assets/vis_gauge'
import { icon as visGoal } from '@elastic/eui/es/components/icon/assets/vis_goal'
import { icon as visLine } from '@elastic/eui/es/components/icon/assets/vis_line'
import { icon as visMapCoordinate } from '@elastic/eui/es/components/icon/assets/vis_map_coordinate'
import { icon as visMapRegion } from '@elastic/eui/es/components/icon/assets/vis_map_region'
import { icon as visMetric } from '@elastic/eui/es/components/icon/assets/vis_metric'
import { icon as visPie } from '@elastic/eui/es/components/icon/assets/vis_pie'
import { icon as visTable } from '@elastic/eui/es/components/icon/assets/vis_table'
import { icon as visTagCloud } from '@elastic/eui/es/components/icon/assets/vis_tag_cloud'
import { icon as visText } from '@elastic/eui/es/components/icon/assets/vis_text'
import { icon as visTimelion } from '@elastic/eui/es/components/icon/assets/vis_timelion'
import { icon as visVisualBuilder } from '@elastic/eui/es/components/icon/assets/vis_visual_builder'
import { icon as warning } from '@elastic/eui/es/components/icon/assets/warning'
import { icon as warningFilled } from '@elastic/eui/es/components/icon/assets/warningFilled'
import { icon as web } from '@elastic/eui/es/components/icon/assets/web'
import { icon as wordWrap } from '@elastic/eui/es/components/icon/assets/wordWrap'
import { icon as wordWrapDisabled } from '@elastic/eui/es/components/icon/assets/wordWrapDisabled'
import { icon as wrench } from '@elastic/eui/es/components/icon/assets/wrench'

appendIconComponentCache({
  'accessibility': accessibility,
  'aggregate': aggregate,
  'alert': alert,
  'analyzeEvent': analyzeEvent,
  'analyze_event': analyzeEvent1,
  'annotation': annotation,
  'anomaly_chart': anomalyChart,
  anomalyChart: anomalyChart,
  'anomaly_swim_lane': anomalySwimLane,
  anomalySwimLane: anomalySwimLane,
  'apm_trace': apmTrace,
  apmTrace: apmTrace,
  'app_add_data': appAddData,
  appAddData: appAddData,
  'app_advanced_settings': appAdvancedSettings,
  appAdvancedSettings: appAdvancedSettings,
  'app_agent': appAgent,
  appAgent: appAgent,
  'app_apm': appApm,
  appApm: appApm,
  'app_app_search': appAppSearch,
  appAppSearch: appAppSearch,
  'app_auditbeat': appAuditbeat,
  appAuditbeat: appAuditbeat,
  'app_canvas': appCanvas,
  appCanvas: appCanvas,
  'app_cases': appCases,
  appCases: appCases,
  'app_code': appCode,
  appCode: appCode,
  'app_console': appConsole,
  appConsole: appConsole,
  'app_cross_cluster_replication': appCrossClusterReplication,
  appCrossClusterReplication: appCrossClusterReplication,
  'app_dashboard': appDashboard,
  appDashboard: appDashboard,
  'app_devtools': appDevtools,
  appDevtools: appDevtools,
  'app_discover': appDiscover,
  appDiscover: appDiscover,
  'app_ems': appEms,
  appEms: appEms,
  'app_filebeat': appFilebeat,
  appFilebeat: appFilebeat,
  'app_fleet': appFleet,
  appFleet: appFleet,
  'app_gis': appGis,
  appGis: appGis,
  'app_graph': appGraph,
  appGraph: appGraph,
  'app_grok': appGrok,
  appGrok: appGrok,
  'app_heartbeat': appHeartbeat,
  appHeartbeat: appHeartbeat,
  'app_index_management': appIndexManagement,
  appIndexManagement: appIndexManagement,
  'app_index_pattern': appIndexPattern,
  appIndexPattern: appIndexPattern,
  'app_index_rollup': appIndexRollup,
  appIndexRollup: appIndexRollup,
  'app_lens': appLens,
  appLens: appLens,
  'app_logs': appLogs,
  appLogs: appLogs,
  'app_management': appManagement,
  appManagement: appManagement,
  'app_metricbeat': appMetricbeat,
  appMetricbeat: appMetricbeat,
  'app_metrics': appMetrics,
  appMetrics: appMetrics,
  'app_ml': appMl,
  appMl: appMl,
  'app_monitoring': appMonitoring,
  appMonitoring: appMonitoring,
  'app_notebook': appNotebook,
  appNotebook: appNotebook,
  'app_packetbeat': appPacketbeat,
  appPacketbeat: appPacketbeat,
  'app_pipeline': appPipeline,
  appPipeline: appPipeline,
  'app_recently_viewed': appRecentlyViewed,
  appRecentlyViewed: appRecentlyViewed,
  'app_reporting': appReporting,
  appReporting: appReporting,
  'app_saved_objects': appSavedObjects,
  appSavedObjects: appSavedObjects,
  'app_search_profiler': appSearchProfiler,
  appSearchProfiler: appSearchProfiler,
  'app_security': appSecurity,
  appSecurity: appSecurity,
  'app_security_analytics': appSecurityAnalytics,
  appSecurityAnalytics: appSecurityAnalytics,
  'app_spaces': appSpaces,
  appSpaces: appSpaces,
  'app_sql': appSql,
  appSql: appSql,
  'app_timelion': appTimelion,
  appTimelion: appTimelion,
  'app_upgrade_assistant': appUpgradeAssistant,
  appUpgradeAssistant: appUpgradeAssistant,
  'app_uptime': appUptime,
  appUptime: appUptime,
  'app_users_roles': appUsersRoles,
  appUsersRoles: appUsersRoles,
  'app_visualize': appVisualize,
  appVisualize: appVisualize,
  'app_vulnerability_management': appVulnerabilityManagement,
  appVulnerabilityManagement: appVulnerabilityManagement,
  'app_watches': appWatches,
  appWatches: appWatches,
  'app_workflows': appWorkflows,
  appWorkflows: appWorkflows,
  'app_workplace_search': appWorkplaceSearch,
  appWorkplaceSearch: appWorkplaceSearch,
  'apps': apps,
  'arrowEnd': arrowEnd,
  'arrowStart': arrowStart,
  'arrow_down': arrowDown,
  arrowDown: arrowDown,
  'arrow_left': arrowLeft,
  arrowLeft: arrowLeft,
  'arrow_right': arrowRight,
  arrowRight: arrowRight,
  'arrow_up': arrowUp,
  arrowUp: arrowUp,
  'article': article,
  'asterisk': asterisk,
  'at': at,
  'background_task': backgroundTask,
  backgroundTask: backgroundTask,
  'bell': bell,
  'bellSlash': bellSlash,
  'beta': beta,
  'bolt': bolt,
  'boxes_horizontal': boxesHorizontal,
  boxesHorizontal: boxesHorizontal,
  'boxes_vertical': boxesVertical,
  boxesVertical: boxesVertical,
  'branch': branch,
  'branchUser': branchUser,
  'broom': broom,
  'brush': brush,
  'bug': bug,
  'bullseye': bullseye,
  'calendar': calendar,
  'change_point_detection': changePointDetection,
  changePointDetection: changePointDetection,
  'check': check,
  'checkCircle': checkCircle,
  'checkInCircleFilled': checkInCircleFilled,
  'cheer': cheer,
  'clickLeft': clickLeft,
  'clickRight': clickRight,
  'clock': clock,
  'clockCounter': clockCounter,
  'cloudDrizzle': cloudDrizzle,
  'cloudStormy': cloudStormy,
  'cloudSunny': cloudSunny,
  'cluster': cluster,
  'code': code,
  'color': color,
  'comment': comment,
  'compute': compute,
  'console': console,
  'container': container,
  'continuityAbove': continuityAbove,
  'continuityAboveBelow': continuityAboveBelow,
  'continuityBelow': continuityBelow,
  'continuityWithin': continuityWithin,
  'contrast': contrast,
  'contrastHigh': contrastHigh,
  'controls': controls,
  'copy': copy,
  'copy_clipboard': copyClipboard,
  copyClipboard: copyClipboard,
  'cross': cross,
  'crossInCircle': crossInCircle,
  'cross_in_circle': crossInCircle1,
  'crosshairs': crosshairs,
  'currency': currency,
  'cut': cut,
  'database': database,
  'desktop': desktop,
  'diff': diff,
  'document': document,
  'documentEdit': documentEdit,
  'documentation': documentation,
  'documents': documents,
  'dot': dot,
  'dotInCircle': dotInCircle,
  'doubleArrowLeft': doubleArrowLeft,
  'doubleArrowRight': doubleArrowRight,
  'download': download,
  'editorDistributeHorizontal': editorDistributeHorizontal,
  'editorDistributeVertical': editorDistributeVertical,
  'editorItemAlignBottom': editorItemAlignBottom,
  'editorItemAlignCenter': editorItemAlignCenter,
  'editorItemAlignLeft': editorItemAlignLeft,
  'editorItemAlignMiddle': editorItemAlignMiddle,
  'editorItemAlignRight': editorItemAlignRight,
  'editorItemAlignTop': editorItemAlignTop,
  'editorPositionBottomLeft': editorPositionBottomLeft,
  'editorPositionBottomRight': editorPositionBottomRight,
  'editorPositionTopLeft': editorPositionTopLeft,
  'editorPositionTopRight': editorPositionTopRight,
  'editor_align_center': editorAlignCenter,
  editorAlignCenter: editorAlignCenter,
  'editor_align_left': editorAlignLeft,
  editorAlignLeft: editorAlignLeft,
  'editor_align_right': editorAlignRight,
  editorAlignRight: editorAlignRight,
  'editor_bold': editorBold,
  editorBold: editorBold,
  'editor_checklist': editorChecklist,
  editorChecklist: editorChecklist,
  'editor_heading': editorHeading,
  editorHeading: editorHeading,
  'editor_italic': editorItalic,
  editorItalic: editorItalic,
  'editor_link': editorLink,
  editorLink: editorLink,
  'editor_ordered_list': editorOrderedList,
  editorOrderedList: editorOrderedList,
  'editor_redo': editorRedo,
  editorRedo: editorRedo,
  'editor_strike': editorStrike,
  editorStrike: editorStrike,
  'editor_table': editorTable,
  editorTable: editorTable,
  'editor_underline': editorUnderline,
  editorUnderline: editorUnderline,
  'editor_undo': editorUndo,
  editorUndo: editorUndo,
  'editor_unordered_list': editorUnorderedList,
  editorUnorderedList: editorUnorderedList,
  'email': email,
  'empty': empty,
  'endpoint': endpoint,
  'eql': eql,
  'eraser': eraser,
  'error': error,
  'errorFilled': errorFilled,
  'esqlVis': esqlVis,
  'exit': exit,
  'expand': expand,
  'expandMini': expandMini,
  'export': exportIcon,
  'eye': eye,
  'eye_closed': eyeClosed,
  eyeClosed: eyeClosed,
  'face_happy': faceHappy,
  faceHappy: faceHappy,
  'face_neutral': faceNeutral,
  faceNeutral: faceNeutral,
  'face_sad': faceSad,
  faceSad: faceSad,
  'field_statistics': fieldStatistics,
  fieldStatistics: fieldStatistics,
  'filter': filter,
  'filterExclude': filterExclude,
  'filterIgnore': filterIgnore,
  'filterInCircle': filterInCircle,
  'filterInclude': filterInclude,
  'flag': flag,
  'flask': flask,
  'fold': fold,
  'folder_check': folderCheck,
  folderCheck: folderCheck,
  'folder_closed': folderClosed,
  folderClosed: folderClosed,
  'folder_exclamation': folderExclamation,
  folderExclamation: folderExclamation,
  'folder_open': folderOpen,
  folderOpen: folderOpen,
  'frameNext': frameNext,
  'framePrevious': framePrevious,
  'fullScreenExit': fullScreenExit,
  'full_screen': fullScreen,
  fullScreen: fullScreen,
  'function': functionIcon,
  'gear': gear,
  'globe': globe,
  'grab': grab,
  'grabOmnidirectional': grabOmnidirectional,
  'grab_horizontal': grabHorizontal,
  grabHorizontal: grabHorizontal,
  'gradient': gradient,
  'grid': grid,
  'heart': heart,
  'heatmap': heatmap,
  'help': help,
  'home': home,
  'image': image,
  'import': importIcon,
  'index': index,
  'indexTemporary': indexTemporary,
  'index_close': indexClose,
  indexClose: indexClose,
  'index_edit': indexEdit,
  indexEdit: indexEdit,
  'index_flush': indexFlush,
  indexFlush: indexFlush,
  'index_mapping': indexMapping,
  indexMapping: indexMapping,
  'index_open': indexOpen,
  indexOpen: indexOpen,
  'index_runtime': indexRuntime,
  indexRuntime: indexRuntime,
  'index_settings': indexSettings,
  indexSettings: indexSettings,
  'infinity': infinity,
  'info': info,
  'inputOutput': inputOutput,
  'inspect': inspect,
  'invert': invert,
  'ip': ip,
  'issue': issue,
  'key': key,
  'keyboard': keyboard,
  'kql_field': kqlField,
  kqlField: kqlField,
  'kql_function': kqlFunction,
  kqlFunction: kqlFunction,
  'kql_operand': kqlOperand,
  kqlOperand: kqlOperand,
  'kql_selector': kqlSelector,
  kqlSelector: kqlSelector,
  'kql_value': kqlValue,
  kqlValue: kqlValue,
  'kubernetesNode': kubernetesNode,
  'kubernetesPod': kubernetesPod,
  'launch': launch,
  'layers': layers,
  'lettering': lettering,
  'lineDashed': lineDashed,
  'lineDotted': lineDotted,
  'lineSolid': lineSolid,
  'link': link,
  'list': list,
  'list_add': listAdd,
  listAdd: listAdd,
  'lock': lock,
  'lockOpen': lockOpen,
  'log_pattern_analysis': logPatternAnalysis,
  logPatternAnalysis: logPatternAnalysis,
  'log_rate_analysis': logRateAnalysis,
  logRateAnalysis: logRateAnalysis,
  'logo_aerospike': logoAerospike,
  logoAerospike: logoAerospike,
  'logo_apache': logoApache,
  logoApache: logoApache,
  'logo_app_search': logoAppSearch,
  logoAppSearch: logoAppSearch,
  'logo_aws': logoAws,
  logoAws: logoAws,
  'logo_aws_mono': logoAwsMono,
  logoAwsMono: logoAwsMono,
  'logo_azure': logoAzure,
  logoAzure: logoAzure,
  'logo_azure_mono': logoAzureMono,
  logoAzureMono: logoAzureMono,
  'logo_beats': logoBeats,
  logoBeats: logoBeats,
  'logo_business_analytics': logoBusinessAnalytics,
  logoBusinessAnalytics: logoBusinessAnalytics,
  'logo_ceph': logoCeph,
  logoCeph: logoCeph,
  'logo_cloud': logoCloud,
  logoCloud: logoCloud,
  'logo_cloud_ece': logoCloudEce,
  logoCloudEce: logoCloudEce,
  'logo_code': logoCode,
  logoCode: logoCode,
  'logo_codesandbox': logoCodesandbox,
  logoCodesandbox: logoCodesandbox,
  'logo_couchbase': logoCouchbase,
  logoCouchbase: logoCouchbase,
  'logo_docker': logoDocker,
  logoDocker: logoDocker,
  'logo_dropwizard': logoDropwizard,
  logoDropwizard: logoDropwizard,
  'logo_elastic': logoElastic,
  logoElastic: logoElastic,
  'logo_elastic_stack': logoElasticStack,
  logoElasticStack: logoElasticStack,
  'logo_elasticsearch': logoElasticsearch,
  logoElasticsearch: logoElasticsearch,
  'logo_enterprise_search': logoEnterpriseSearch,
  logoEnterpriseSearch: logoEnterpriseSearch,
  'logo_etcd': logoEtcd,
  logoEtcd: logoEtcd,
  'logo_gcp': logoGcp,
  logoGcp: logoGcp,
  'logo_gcp_mono': logoGcpMono,
  logoGcpMono: logoGcpMono,
  'logo_github': logoGithub,
  logoGithub: logoGithub,
  'logo_gmail': logoGmail,
  logoGmail: logoGmail,
  'logo_golang': logoGolang,
  logoGolang: logoGolang,
  'logo_google_g': logoGoogleG,
  logoGoogleG: logoGoogleG,
  'logo_haproxy': logoHaproxy,
  logoHaproxy: logoHaproxy,
  'logo_ibm': logoIbm,
  logoIbm: logoIbm,
  'logo_ibm_mono': logoIbmMono,
  logoIbmMono: logoIbmMono,
  'logo_kafka': logoKafka,
  logoKafka: logoKafka,
  'logo_kibana': logoKibana,
  logoKibana: logoKibana,
  'logo_kubernetes': logoKubernetes,
  logoKubernetes: logoKubernetes,
  'logo_logging': logoLogging,
  logoLogging: logoLogging,
  'logo_logstash': logoLogstash,
  logoLogstash: logoLogstash,
  'logo_maps': logoMaps,
  logoMaps: logoMaps,
  'logo_memcached': logoMemcached,
  logoMemcached: logoMemcached,
  'logo_metrics': logoMetrics,
  logoMetrics: logoMetrics,
  'logo_mongodb': logoMongodb,
  logoMongodb: logoMongodb,
  'logo_mysql': logoMysql,
  logoMysql: logoMysql,
  'logo_nginx': logoNginx,
  logoNginx: logoNginx,
  'logo_observability': logoObservability,
  logoObservability: logoObservability,
  'logo_osquery': logoOsquery,
  logoOsquery: logoOsquery,
  'logo_php': logoPhp,
  logoPhp: logoPhp,
  'logo_postgres': logoPostgres,
  logoPostgres: logoPostgres,
  'logo_prometheus': logoPrometheus,
  logoPrometheus: logoPrometheus,
  'logo_rabbitmq': logoRabbitmq,
  logoRabbitmq: logoRabbitmq,
  'logo_redis': logoRedis,
  logoRedis: logoRedis,
  'logo_security': logoSecurity,
  logoSecurity: logoSecurity,
  'logo_site_search': logoSiteSearch,
  logoSiteSearch: logoSiteSearch,
  'logo_sketch': logoSketch,
  logoSketch: logoSketch,
  'logo_slack': logoSlack,
  logoSlack: logoSlack,
  'logo_uptime': logoUptime,
  logoUptime: logoUptime,
  'logo_vulnerability_management': logoVulnerabilityManagement,
  logoVulnerabilityManagement: logoVulnerabilityManagement,
  'logo_webhook': logoWebhook,
  logoWebhook: logoWebhook,
  'logo_windows': logoWindows,
  logoWindows: logoWindows,
  'logo_workplace_search': logoWorkplaceSearch,
  logoWorkplaceSearch: logoWorkplaceSearch,
  'logstash_filter': logstashFilter,
  logstashFilter: logstashFilter,
  'logstash_if': logstashIf,
  logstashIf: logstashIf,
  'logstash_input': logstashInput,
  logstashInput: logstashInput,
  'logstash_output': logstashOutput,
  logstashOutput: logstashOutput,
  'logstash_queue': logstashQueue,
  logstashQueue: logstashQueue,
  'magnet': magnet,
  'magnifyWithExclamation': magnifyWithExclamation,
  'magnifyWithMinus': magnifyWithMinus,
  'magnifyWithPlus': magnifyWithPlus,
  'map_marker': mapMarker,
  mapMarker: mapMarker,
  'memory': memory,
  'menu': menu,
  'menuDown': menuDown,
  'menuLeft': menuLeft,
  'menuRight': menuRight,
  'menuUp': menuUp,
  'merge': merge,
  'minimize': minimize,
  'minus': minus,
  'minus_in_circle': minusInCircle,
  minusInCircle: minusInCircle,
  'minus_in_circle_filled': minusInCircleFilled,
  minusInCircleFilled: minusInCircleFilled,
  'minus_in_square': minusInSquare,
  minusInSquare: minusInSquare,
  'ml_classification_job': mlClassificationJob,
  mlClassificationJob: mlClassificationJob,
  'ml_create_advanced_job': mlCreateAdvancedJob,
  mlCreateAdvancedJob: mlCreateAdvancedJob,
  'ml_create_generic_job': mlCreateGenericJob,
  mlCreateGenericJob: mlCreateGenericJob,
  'ml_create_geo_job': mlCreateGeoJob,
  mlCreateGeoJob: mlCreateGeoJob,
  'ml_create_multi_metric_job': mlCreateMultiMetricJob,
  mlCreateMultiMetricJob: mlCreateMultiMetricJob,
  'ml_create_population_job': mlCreatePopulationJob,
  mlCreatePopulationJob: mlCreatePopulationJob,
  'ml_create_single_metric_job': mlCreateSingleMetricJob,
  mlCreateSingleMetricJob: mlCreateSingleMetricJob,
  'ml_data_visualizer': mlDataVisualizer,
  mlDataVisualizer: mlDataVisualizer,
  'ml_outlier_detection_job': mlOutlierDetectionJob,
  mlOutlierDetectionJob: mlOutlierDetectionJob,
  'ml_regression_job': mlRegressionJob,
  mlRegressionJob: mlRegressionJob,
  'mobile': mobile,
  'moon': moon,
  'move': move,
  'namespace': namespace,
  'nested': nested,
  'new_chat': newChat,
  newChat: newChat,
  'node': node,
  'number': number,
  'offline': offline,
  'online': online,
  'package': packageIcon,
  'pageSelect': pageSelect,
  'pagesSelect': pagesSelect,
  'paint': paint,
  'palette': palette,
  'paper_clip': paperClip,
  paperClip: paperClip,
  'partial': partial,
  'pause': pause,
  'payment': payment,
  'pencil': pencil,
  'percent': percent,
  'pin': pin,
  'pin_filled': pinFilled,
  pinFilled: pinFilled,
  'pipeBreaks': pipeBreaks,
  'pipeNoBreaks': pipeNoBreaks,
  'pivot': pivot,
  'play': play,
  'playFilled': playFilled,
  'plugs': plugs,
  'plus': plus,
  'plus_in_circle': plusInCircle,
  plusInCircle: plusInCircle,
  'plus_in_circle_filled': plusInCircleFilled,
  plusInCircleFilled: plusInCircleFilled,
  'plus_in_square': plusInSquare,
  plusInSquare: plusInSquare,
  'popout': popout,
  'push': push,
  'question': question,
  'quote': quote,
  'readOnly': readOnly,
  'refresh': refresh,
  'reporter': reporter,
  'return_key': returnKey,
  returnKey: returnKey,
  'save': save,
  'scale': scale,
  'search': search,
  'section': section,
  'securitySignal': securitySignal,
  'securitySignalDetected': securitySignalDetected,
  'securitySignalResolved': securitySignalResolved,
  'sessionViewer': sessionViewer,
  'shard': shard,
  'share': share,
  'single_metric_viewer': singleMetricViewer,
  singleMetricViewer: singleMetricViewer,
  'snowflake': snowflake,
  'sortAscending': sortAscending,
  'sortDescending': sortDescending,
  'sortLeft': sortLeft,
  'sortRight': sortRight,
  'sort_down': sortDown,
  sortDown: sortDown,
  'sort_up': sortUp,
  sortUp: sortUp,
  'sortable': sortable,
  'spaces': spaces,
  'sparkles': sparkles,
  'starPlusEmpty': starPlusEmpty,
  'starPlusFilled': starPlusFilled,
  'star_empty': starEmpty,
  starEmpty: starEmpty,
  'star_empty_space': starEmptySpace,
  starEmptySpace: starEmptySpace,
  'star_filled': starFilled,
  starFilled: starFilled,
  'star_filled_space': starFilledSpace,
  starFilledSpace: starFilledSpace,
  'star_minus_empty': starMinusEmpty,
  starMinusEmpty: starMinusEmpty,
  'star_minus_filled': starMinusFilled,
  starMinusFilled: starMinusFilled,
  'stats': stats,
  'stop': stop,
  'stop_filled': stopFilled,
  stopFilled: stopFilled,
  'stop_slash': stopSlash,
  stopSlash: stopSlash,
  'storage': storage,
  'streams_classic': streamsClassic,
  streamsClassic: streamsClassic,
  'streams_wired': streamsWired,
  streamsWired: streamsWired,
  'string': string,
  'submodule': submodule,
  'sun': sun,
  'swatch_input': swatchInput,
  swatchInput: swatchInput,
  'symlink': symlink,
  'tableOfContents': tableOfContents,
  'table_density_compact': tableDensityCompact,
  tableDensityCompact: tableDensityCompact,
  'table_density_expanded': tableDensityExpanded,
  tableDensityExpanded: tableDensityExpanded,
  'table_density_normal': tableDensityNormal,
  tableDensityNormal: tableDensityNormal,
  'tag': tag,
  'tear': tear,
  'temperature': temperature,
  'thumbDown': thumbDown,
  'thumbUp': thumbUp,
  'timeRefresh': timeRefresh,
  'timeline': timeline,
  'timelineWithArrow': timelineWithArrow,
  'timeslider': timeslider,
  'tokenAlias': tokenAlias,
  'tokenAnnotation': tokenAnnotation,
  'tokenArray': tokenArray,
  'tokenBinary': tokenBinary,
  'tokenBoolean': tokenBoolean,
  'tokenClass': tokenClass,
  'tokenCompletionSuggester': tokenCompletionSuggester,
  'tokenConstant': tokenConstant,
  'tokenDate': tokenDate,
  'tokenDimension': tokenDimension,
  'tokenElement': tokenElement,
  'tokenEnum': tokenEnum,
  'tokenEnumMember': tokenEnumMember,
  'tokenEvent': tokenEvent,
  'tokenException': tokenException,
  'tokenField': tokenField,
  'tokenFile': tokenFile,
  'tokenFlattened': tokenFlattened,
  'tokenFunction': tokenFunction,
  'tokenGeo': tokenGeo,
  'tokenHistogram': tokenHistogram,
  'tokenIP': tokenIP,
  'tokenInterface': tokenInterface,
  'tokenJoin': tokenJoin,
  'tokenKey': tokenKey,
  'tokenKeyword': tokenKeyword,
  'tokenMethod': tokenMethod,
  'tokenMetricCounter': tokenMetricCounter,
  'tokenMetricGauge': tokenMetricGauge,
  'tokenModule': tokenModule,
  'tokenNamespace': tokenNamespace,
  'tokenNested': tokenNested,
  'tokenNull': tokenNull,
  'tokenNumber': tokenNumber,
  'tokenObject': tokenObject,
  'tokenOperator': tokenOperator,
  'tokenPackage': tokenPackage,
  'tokenParameter': tokenParameter,
  'tokenPercolator': tokenPercolator,
  'tokenProperty': tokenProperty,
  'tokenRange': tokenRange,
  'tokenRankFeature': tokenRankFeature,
  'tokenRankFeatures': tokenRankFeatures,
  'tokenRepo': tokenRepo,
  'tokenSearchType': tokenSearchType,
  'tokenSemanticText': tokenSemanticText,
  'tokenShape': tokenShape,
  'tokenString': tokenString,
  'tokenStruct': tokenStruct,
  'tokenSymbol': tokenSymbol,
  'tokenTag': tokenTag,
  'tokenText': tokenText,
  'tokenTokenCount': tokenTokenCount,
  'tokenVariable': tokenVariable,
  'tokenVectorDense': tokenVectorDense,
  'tokenVectorSparse': tokenVectorSparse,
  'training': training,
  'transitionLeftIn': transitionLeftIn,
  'transitionLeftOut': transitionLeftOut,
  'transitionTopIn': transitionTopIn,
  'transitionTopOut': transitionTopOut,
  'trash': trash,
  'unfold': unfold,
  'unlink': unlink,
  'user': user,
  'users': users,
  'vector': vector,
  'videoPlayer': videoPlayer,
  'vis_area': visArea,
  visArea: visArea,
  'vis_area_stacked': visAreaStacked,
  visAreaStacked: visAreaStacked,
  'vis_bar_horizontal': visBarHorizontal,
  visBarHorizontal: visBarHorizontal,
  'vis_bar_horizontal_stacked': visBarHorizontalStacked,
  visBarHorizontalStacked: visBarHorizontalStacked,
  'vis_bar_vertical': visBarVertical,
  visBarVertical: visBarVertical,
  'vis_bar_vertical_stacked': visBarVerticalStacked,
  visBarVerticalStacked: visBarVerticalStacked,
  'vis_gauge': visGauge,
  visGauge: visGauge,
  'vis_goal': visGoal,
  visGoal: visGoal,
  'vis_line': visLine,
  visLine: visLine,
  'vis_map_coordinate': visMapCoordinate,
  visMapCoordinate: visMapCoordinate,
  'vis_map_region': visMapRegion,
  visMapRegion: visMapRegion,
  'vis_metric': visMetric,
  visMetric: visMetric,
  'vis_pie': visPie,
  visPie: visPie,
  'vis_table': visTable,
  visTable: visTable,
  'vis_tag_cloud': visTagCloud,
  visTagCloud: visTagCloud,
  'vis_text': visText,
  visText: visText,
  'vis_timelion': visTimelion,
  visTimelion: visTimelion,
  'vis_visual_builder': visVisualBuilder,
  visVisualBuilder: visVisualBuilder,
  'warning': warning,
  'warningFilled': warningFilled,
  'web': web,
  'wordWrap': wordWrap,
  'wordWrapDisabled': wordWrapDisabled,
  'wrench': wrench
})

// All 520 EUI icons are now available
