#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml>=6.0"]
# ///
"""
Project Context Module

Manages the `project-context.yaml` file that stores project metadata,
use case information, and configuration choices.

This file serves as the single source of truth for:
- Project name and goal (for telemetry and AI context)
- Delivery method and capabilities
- Branding configuration
- Data source information

Both the setup wizard and AI-guided onboarding write to this file.

Note: Requires PyYAML. When run via `uv run`, the inline script dependencies
above ensure PyYAML is automatically installed.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

logger = logging.getLogger(__name__)

PROJECT_CONTEXT_FILE = "project-context.yaml"


@dataclass
class ProjectContext:
    """Project context data model."""
    
    # Project identification
    name: Optional[str] = None
    goal: Optional[str] = None
    customer: Optional[str] = None
    
    # Delivery method: standalone, overlay, widget
    delivery_type: Optional[str] = None
    
    # Capabilities enabled
    capabilities: List[str] = field(default_factory=list)
    
    # Branding
    branding_url: Optional[str] = None
    branding_name: Optional[str] = None
    
    # Data configuration
    data_index: Optional[str] = None
    data_source: Optional[str] = None  # existing, ingest, sample
    
    # Metadata
    created: Optional[str] = None
    updated: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for YAML serialisation."""
        data: Dict[str, Any] = {}
        
        if self.name:
            data["name"] = self.name
        if self.goal:
            data["goal"] = self.goal
        if self.customer:
            data["customer"] = self.customer
        if self.delivery_type:
            data["delivery_type"] = self.delivery_type
        if self.capabilities:
            data["capabilities"] = self.capabilities
        if self.branding_url:
            data["branding_url"] = self.branding_url
        if self.branding_name:
            data["branding_name"] = self.branding_name
        if self.data_index:
            data["data_index"] = self.data_index
        if self.data_source:
            data["data_source"] = self.data_source
        if self.created:
            data["created"] = self.created
        if self.updated:
            data["updated"] = self.updated
        
        return data
    
    def to_yaml(self) -> str:
        """Convert to YAML string."""
        header = (
            "# Project Context\n"
            "# Auto-generated by setup wizard / AI onboarding\n"
            "# Used for telemetry, AI context, and project documentation\n\n"
        )
        
        return header + yaml.dump(
            self.to_dict(),
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )
    
    @classmethod
    def from_yaml(cls, content: str) -> "ProjectContext":
        """Parse from YAML string."""
        data = yaml.safe_load(content) or {}
        return cls.from_dict(data)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ProjectContext":
        """Create from dictionary."""
        return cls(
            name=data.get("name"),
            goal=data.get("goal"),
            customer=data.get("customer"),
            delivery_type=data.get("delivery_type"),
            capabilities=data.get("capabilities", []),
            branding_url=data.get("branding_url"),
            branding_name=data.get("branding_name"),
            data_index=data.get("data_index"),
            data_source=data.get("data_source"),
            created=data.get("created"),
            updated=data.get("updated"),
        )
    
    def get_use_case_summary(self) -> Optional[str]:
        """
        Generate a use case summary from the context.
        
        Returns a human-readable string suitable for telemetry.
        """
        parts = []
        
        if self.goal:
            return self.goal  # Goal is the best summary
        
        # Fallback: construct from parts
        if self.name:
            parts.append(self.name)
        
        if self.capabilities:
            cap_str = " + ".join(self.capabilities)
            parts.append(f"({cap_str})")
        
        if self.customer:
            parts.append(f"for {self.customer}")
        elif self.branding_name:
            parts.append(f"for {self.branding_name}")
        
        return " ".join(parts) if parts else None


def get_context_path(base_dir: Optional[str] = None) -> Path:
    """Get the path to the project context file."""
    if base_dir:
        return Path(base_dir) / PROJECT_CONTEXT_FILE
    return Path(PROJECT_CONTEXT_FILE)


def load_context(base_dir: Optional[str] = None) -> Optional[ProjectContext]:
    """
    Load project context from file.
    
    Returns None if file doesn't exist or is invalid.
    """
    path = get_context_path(base_dir)
    
    if not path.exists():
        return None
    
    try:
        content = path.read_text()
        return ProjectContext.from_yaml(content)
    except Exception as e:
        logger.debug(f"Failed to load project context from {path}: {e}")
        return None


def save_context(ctx: ProjectContext, base_dir: Optional[str] = None) -> bool:
    """
    Save project context to file.
    
    Updates the 'updated' timestamp automatically.
    Returns True on success.
    """
    path = get_context_path(base_dir)
    
    # Set timestamps
    now = datetime.now(timezone.utc).isoformat()
    if not ctx.created:
        ctx.created = now
    ctx.updated = now
    
    try:
        path.write_text(ctx.to_yaml())
        return True
    except Exception as e:
        logger.debug(f"Failed to save project context to {path}: {e}")
        return False


def update_context(base_dir: Optional[str] = None, **kwargs) -> ProjectContext:
    """
    Load existing context, update with kwargs, and save.
    
    Creates new context if none exists.
    Returns the updated context.
    """
    ctx = load_context(base_dir) or ProjectContext()
    
    for key, value in kwargs.items():
        if hasattr(ctx, key) and value is not None:
            setattr(ctx, key, value)
    
    save_context(ctx, base_dir)
    return ctx


# =============================================================================
# CLI Test
# =============================================================================

if __name__ == "__main__":
    print("Testing project_context module...\n")
    
    # Create a test context
    ctx = ProjectContext(
        name="Acme Product Search",
        goal="E-commerce search with AI recommendations for shoe retailer",
        customer="Acme Corp",
        delivery_type="standalone",
        capabilities=["search", "agent_chat", "analytics"],
        branding_url="https://acme.com",
        branding_name="acme",
        data_index="products",
        data_source="existing",
    )
    
    # Test to_yaml
    yaml_str = ctx.to_yaml()
    print("Generated YAML:")
    print("-" * 40)
    print(yaml_str)
    print("-" * 40)
    
    # Test from_yaml (round-trip)
    ctx2 = ProjectContext.from_yaml(yaml_str)
    print(f"\nRound-trip test:")
    print(f"  name: {ctx2.name}")
    print(f"  goal: {ctx2.goal}")
    print(f"  capabilities: {ctx2.capabilities}")
    print(f"  branding_url: {ctx2.branding_url}")
    
    # Test get_use_case_summary
    print(f"\nUse case summary: {ctx2.get_use_case_summary()}")
    
    # Test with minimal context
    ctx3 = ProjectContext(capabilities=["search"], branding_name="nike")
    print(f"Minimal summary: {ctx3.get_use_case_summary()}")
